theme = "hugo-theme-casper"
BaseUrl = "/"
publishDir = "public/"
LanguageCode = "en-us"
Title = "Jubarly Studio"
paginate = 5
# DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2020"
canonifyurls = true
enableEmoji = true
comments = true

[[menu.main]]
    name = "About Me"
    url = "/about-me/"

[[menu.main]]
    name = "About This Website"
    url = "/about-this-website/"

[[menu.main]]
    name = "Artist Statement"
    url = "/artist-statement/"

[[menu.main]]
    name = "Categories"
    url = "/categories/"

[[menu.main]]
    name = "Instagram"
    url = "https://www.instagram.com/jubarlystudio"

[[menu.main]]
    name = "Tags"
    url = "/tags/"

[params]
    # description = "Jubarly Studio"
    cover = "images/profile/erlangen.jpg"

    author = "Jubarly Studio"
    authorlocation = "Berlin, Germany"
    # googleAnalyticsUserID = "UA-79101-12"

    logo = "images/profile/portrait_of_baby.jpg"
    hideHUGOSupport = true

    # twitterName = "weichunchu01"
    # instagramName = "jubarlystudio"
    # githubName = "wcchu"

    # Setting a value will load highlight.js and enable syntax highlighting using the style selected.
    # See https://github.com/isagalaev/highlight.js/tree/master/src/styles for available styles
    # A preview of above styles can be viewed at https://highlightjs.org/static/demo/
    hjsStyle = "default"

# [param.social]
    # github  = "https://github.com/wcchu"
    # twitter = "https://twitter.com/weichunchu01"
    # instagram = "https://www.instagram.com/jubarlystudio"
    # soundcloud = "https://soundcloud.com/wcchu"
